import { MetadataRoute } from 'next'
import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { PROJECTS } from '@/lib/projects'
import { LOCATIONS } from '@/lib/locations'
import CONTENT_DATES from '@/lib/content-dates.json'
import nextConfig from '../next.config.mjs'

// next.config.mjs is plain ESM, so its inferred type doesn't guarantee the
// optional `redirects()` factory is present. Narrow it locally instead of
// suppressing, so a config refactor surfaces as a type error here.
type RedirectRule = {
  source?: string
  has?: unknown[]
  missing?: unknown[]
}
const configWithRedirects = nextConfig as {
  redirects?: () => Promise<RedirectRule[]>
}

const baseUrl = 'https://houstonsuperiorpainting.com'

/**
 * Every route that next.config.mjs redirects away, read from the config itself.
 *
 * A redirected URL must never appear in the sitemap: Google reports those as
 * "Page with redirect" and drops them. Redirect sources still have real page
 * files on disk, so the filesystem walker below cannot tell they're dead — and
 * isRedirectOnlyPage() only catches pages that call redirect() in their own
 * source, not config-level rules.
 *
 * This used to be a hand-maintained list, which silently drifted: six indexed
 * URLs (/interior-painting-houston, /exterior-painting-houston,
 * /commercial-painting-houston, /cabinet-refinishing-houston,
 * /drywall-repair-houston, /cabinet-painting-houston-tx) were being 301'd and
 * advertised in the sitemap at the same time. Deriving the set from the config
 * means adding a redirect automatically removes it from the sitemap.
 *
 * Only literal single-segment sources are collected. Pattern sources (`:path*`,
 * regex groups) and host-conditional rules don't map to one static route, and
 * the routes they'd affect are handled by EXCLUDED_TREES / EXCLUDED instead.
 */
async function redirectedRoutes(): Promise<Set<string>> {
  const routes = new Set<string>()
  try {
    const rules = (await configWithRedirects.redirects?.()) ?? []
    for (const rule of rules) {
      const source: string = rule?.source ?? ''
      // Skip patterns and host-scoped rules — they aren't a single static route.
      if (!source.startsWith('/') || /[:*(){}[\]?+]/.test(source)) continue
      if (Array.isArray(rule.has) || Array.isArray(rule.missing)) continue
      const route = source.slice(1)
      if (route) routes.add(route)
    }
  } catch {
    // If the config can't be read, fall back to EXCLUDED alone rather than
    // failing the build — a slightly stale sitemap beats no sitemap.
  }
  return routes
}

/**
 * Resolve an honest "last modified" date for a route, or null if we don't know.
 *
 * Order: committed snapshot -> live git history -> null (omit <lastmod>).
 *
 * The mtime fallback that used to live here was actively harmful. On Vercel the
 * build checkout is a SHALLOW clone, so `git log -- <path>` returns nothing for
 * nearly every file and mtime took over — and because every file is written at
 * checkout time, all 166 sitemap URLs got stamped with the same deploy instant.
 * The sitemap therefore claimed the whole site changed on every single deploy
 * (verified live: 160 of 166 URLs shared one timestamp).
 *
 * Google only honours <lastmod> while it looks consistently accurate; a sitemap
 * that cries "everything changed just now" every deploy teaches it to discount
 * the signal site-wide, which *delays* recrawl of pages that genuinely changed.
 * Omitting the field is strictly better than lying about it — Google simply
 * falls back to its own heuristics instead of distrusting the whole file.
 *
 * lib/content-dates.json is generated by scripts/generate-content-dates.mjs in
 * an environment with full history, so production never depends on git.
 */
const gitDateCache = new Map<string, Date | null>()
function contentDateFor(route: string, filePath: string): Date | null {
  const snapshot = (CONTENT_DATES as Record<string, string>)[route]
  if (snapshot) {
    const d = new Date(snapshot)
    if (!Number.isNaN(d.getTime())) return d
  }

  if (!gitDateCache.has(filePath)) {
    let resolved: Date | null = null
    try {
      const out = execFileSync(
        'git',
        ['log', '-1', '--format=%cI', '--', filePath],
        { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] },
      ).trim()
      if (out) {
        const d = new Date(out)
        if (!Number.isNaN(d.getTime())) resolved = d
      }
    } catch {
      // git unavailable (shallow clone / no .git) — leave null and omit lastmod.
    }
    gitDateCache.set(filePath, resolved)
  }
  return gitDateCache.get(filePath) ?? null
}

// Routes that should never appear in the sitemap (API routes, dynamic
// segments, route groups, and private folders are excluded automatically).
//
// isRedirectOnlyPage() below only catches pages that call redirect() in their
// own source. Routes redirected in next.config.mjs still have a real page file
// on disk, so they must be listed here by hand or the sitemap advertises a URL
// that immediately 308s — Google reports those as "Page with redirect" and
// drops them from the index.
const EXCLUDED = new Set([
  'blog', // /blog index is added explicitly below
  'garage-epoxy-houston-tx', // 308s to houstonsuperiorepoxy.com
  // The old epoxy microsite. Its page files are deliberately still on disk as a
  // reference after the brand moved to its own domain, so the walker would
  // otherwise keep advertising a URL that now 308s off-site.
  'epoxy',
  // Post-conversion thank-you page. It sets robots noindex in its own metadata,
  // so listing it here keeps the sitemap from contradicting that directive —
  // Google flags "Submitted URL marked noindex" as an error otherwise.
  'estimate-confirmed',
])

// Whole subtrees to skip, matched against the top-level segment. Unlike
// EXCLUDED (which matches one exact route), this also stops the walker
// recursing in, so pages added under these paths later are excluded
// automatically rather than silently appearing in the sitemap.
const EXCLUDED_TREES = new Set([
  // Paid-traffic ad landing pages. Every page under /chatgpt/ is deliberately
  // noindex — the matching organic service pages already rank, and indexing
  // near-duplicates would split ranking signals between two of our own URLs.
  // See docs/seo-audit-2026-08.md §6.
  'chatgpt',
])

// Per-route priority/changeFrequency hints. Anything not listed falls back to
// sensible defaults based on its path prefix.
function routeMeta(route: string): {
  priority: number
  changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency']
} {
  if (route === '') return { priority: 1, changeFrequency: 'weekly' }
  if (route === 'contact') return { priority: 0.9, changeFrequency: 'monthly' }
  // Paid-traffic conversion landing page — also a strong organic target for
  // "painting estimate houston" intent queries.
  if (route === 'painting-estimate-houston')
    return { priority: 0.9, changeFrequency: 'monthly' }
  if (route === 'about') return { priority: 0.8, changeFrequency: 'monthly' }
  if (route === 'privacy-policy' || route === 'terms-and-conditions')
    return { priority: 0.3, changeFrequency: 'yearly' }
  if (route.startsWith('blog/')) return { priority: 0.7, changeFrequency: 'monthly' }
  // Core service hubs (…-houston-tx) rank highest among service pages.
  if (route.endsWith('-houston-tx')) return { priority: 0.9, changeFrequency: 'monthly' }
  if (route.startsWith('painters-')) return { priority: 0.8, changeFrequency: 'monthly' }
  return { priority: 0.8, changeFrequency: 'monthly' }
}

/**
 * Detect pages whose only job is to redirect (legacy/duplicate URLs that call
 * redirect() or permanentRedirect() from next/navigation). These should not be
 * advertised in the sitemap since they 3xx away immediately.
 */
function isRedirectOnlyPage(filePath: string): boolean {
  try {
    const src = fs.readFileSync(filePath, 'utf8')
    return (
      /\b(?:permanentRedirect|redirect)\s*\(/.test(src) &&
      /from\s+['"]next\/navigation['"]/.test(src)
    )
  } catch {
    return false
  }
}

/**
 * Recursively walk the /app directory and collect every static route that has
 * a page file. Dynamic routes ([slug]), route groups ((group)), private
 * folders (_folder) and API routes are skipped so the sitemap stays in sync
 * with the filesystem automatically — no manual list to maintain.
 */
function collectRoutes(
  dir: string,
  prefix: string,
  acc: { route: string; lastModified: Date | null }[],
  excluded: Set<string>,
) {
  const entries = fs.readdirSync(dir, { withFileTypes: true })

  const hasPage = entries.some(
    (e) => e.isFile() && /^page\.(tsx|ts|jsx|js|mdx)$/.test(e.name),
  )
  if (hasPage && !excluded.has(prefix)) {
    const pageFile = entries.find(
      (e) => e.isFile() && /^page\.(tsx|ts|jsx|js|mdx)$/.test(e.name),
    )!
    const pagePath = path.join(dir, pageFile.name)
    // Skip redirect-only pages (e.g. legacy URLs that call redirect()/permanentRedirect()).
    // Including them would point crawlers at URLs that immediately 3xx elsewhere.
    if (!isRedirectOnlyPage(pagePath)) {
      acc.push({ route: prefix, lastModified: contentDateFor(prefix, pagePath) })
    }
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue
    const name = entry.name
    // Skip dynamic segments, route groups, private folders, and api.
    if (
      name.startsWith('[') ||
      name.startsWith('(') ||
      name.startsWith('_') ||
      name === 'api' ||
      // Don't descend into deliberately-noindexed subtrees.
      (prefix === '' && EXCLUDED_TREES.has(name))
    ) {
      continue
    }
    collectRoutes(
      path.join(dir, name),
      prefix ? `${prefix}/${name}` : name,
      acc,
      excluded,
    )
  }
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const appDir = path.join(process.cwd(), 'app')
  const collected: { route: string; lastModified: Date | null }[] = []
  // Union of the hand-listed exclusions and every literal redirect source
  // declared in next.config.mjs.
  const excluded = new Set([...EXCLUDED, ...(await redirectedRoutes())])
  collectRoutes(appDir, '', collected, excluded)

  const entries: MetadataRoute.Sitemap = collected.map(({ route, lastModified }) => {
    const { priority, changeFrequency } = routeMeta(route)
    return {
      url: route ? `${baseUrl}/${route}` : baseUrl,
      // Spread so an unknown date omits <lastmod> rather than emitting a
      // fabricated one. See contentDateFor().
      ...(lastModified ? { lastModified } : {}),
      changeFrequency,
      priority,
    }
  })

  // Ensure the /blog index is present (its folder is excluded so child posts
  // don't pull it in twice). Its freshness mirrors the most recently updated
  // blog post rather than the build time.
  const blogDates = collected
    .filter(({ route }) => route.startsWith('blog/'))
    .map(({ lastModified }) => lastModified?.getTime())
    .filter((t): t is number => typeof t === 'number')
  const blogIndexLastModified = blogDates.length
    ? new Date(Math.max(...blogDates))
    : contentDateFor('blog', path.join(appDir, 'blog', 'page.tsx'))
  entries.push({
    url: `${baseUrl}/blog`,
    ...(blogIndexLastModified ? { lastModified: blogIndexLastModified } : {}),
    changeFrequency: 'weekly',
    priority: 0.8,
  })

  // Project case studies live under the dynamic /projects/[slug] route, which
  // collectRoutes() skips. Add each one explicitly from the project data.
  const projectsPageDate = contentDateFor(
    'projects/[slug]',
    path.join(appDir, 'projects', '[slug]', 'page.tsx'),
  )
  for (const project of PROJECTS) {
    entries.push({
      url: `${baseUrl}/projects/${project.slug}`,
      ...(projectsPageDate ? { lastModified: projectsPageDate } : {}),
      changeFrequency: 'monthly',
      priority: 0.7,
    })
  }

  const locationsPageDate = contentDateFor(
    'locations/[slug]',
    path.join(appDir, 'locations', '[slug]', 'page.tsx'),
  )
  for (const location of LOCATIONS) {
    entries.push({
      url: `${baseUrl}/locations/${location.slug}`,
      ...(locationsPageDate ? { lastModified: locationsPageDate } : {}),
      changeFrequency: 'monthly',
      priority: 0.9,
    })
  }

  // Stable ordering: highest priority first, then alphabetical.
  entries.sort((a, b) => (b.priority ?? 0) - (a.priority ?? 0) || a.url.localeCompare(b.url))

  return entries
}
